-- Table: public.estados

-- DROP TABLE IF EXISTS public.estados;

CREATE TABLE IF NOT EXISTS public.estados
(
    fecha_creacion timestamp(6) without time zone,
    fecha_modificacion timestamp(6) without time zone,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_uss bigint,
    usuario_creacion bigint,
    usuario_modificacion bigint,
    contenido character varying(255) COLLATE pg_catalog."default",
    id_creacion character varying(255) COLLATE pg_catalog."default",
    id_modificacion character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT estados_pkey PRIMARY KEY (id),
    CONSTRAINT fkf7gmo6cv6pahljjqk8epsxbyf FOREIGN KEY (id_uss)
        REFERENCES public.usuarios (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.estados
    OWNER to "LUISM";