-- Table: public.usuarios

-- DROP TABLE IF EXISTS public.usuarios;

CREATE TABLE IF NOT EXISTS public.usuarios
(
    fecha_creacion timestamp(6) without time zone,
    fecha_modificacion timestamp(6) without time zone,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    usuario_creacion bigint,
    usuario_modificacion bigint,
    celular character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_creacion character varying(255) COLLATE pg_catalog."default",
    id_modificacion character varying(255) COLLATE pg_catalog."default",
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(255) COLLATE pg_catalog."default" DEFAULT 'A'::character varying,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.usuarios
    OWNER to "LUISM";